// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WheelsApp_Backend.Models;

namespace WheelsApp_Backend.Migrations
{
    [DbContext(typeof(WheelsContext))]
    partial class WheelsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WheelsApp_Backend.Models.Address", b =>
                {
                    b.Property<long>("Address_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Building_name");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("Postal_code");

                    b.Property<string>("Street");

                    b.HasKey("Address_Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("WheelsApp_Backend.Models.NextOfKin", b =>
                {
                    b.Property<long>("Kin_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("Address_Id");

                    b.Property<string>("Telephone");

                    b.Property<string>("Work_telephone");

                    b.HasKey("Kin_id");

                    b.HasIndex("Address_Id");

                    b.ToTable("NextOfKin");
                });

            modelBuilder.Entity("WheelsApp_Backend.Models.User", b =>
                {
                    b.Property<long>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account_status");

                    b.Property<string>("Date_created");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email");

                    b.Property<string>("First_name");

                    b.Property<long>("Id_number");

                    b.Property<string>("Last_name");

                    b.Property<string>("Password");

                    b.Property<int?>("Role");

                    b.Property<string>("Sex");

                    b.Property<string>("Telephone");

                    b.Property<string>("Telephone_2");

                    b.Property<string>("Username");

                    b.HasKey("User_Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("WheelsApp_Backend.Models.Client", b =>
                {
                    b.HasBaseType("WheelsApp_Backend.Models.User");

                    b.Property<long?>("Address_Id");

                    b.Property<string>("Avatar");

                    b.Property<long?>("Next_of_kinKin_id");

                    b.Property<int>("Token");

                    b.Property<string>("Work_telephone");

                    b.HasIndex("Address_Id");

                    b.HasIndex("Next_of_kinKin_id");

                    b.HasDiscriminator().HasValue("Client");
                });

            modelBuilder.Entity("WheelsApp_Backend.Models.NextOfKin", b =>
                {
                    b.HasOne("WheelsApp_Backend.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("Address_Id");
                });

            modelBuilder.Entity("WheelsApp_Backend.Models.Client", b =>
                {
                    b.HasOne("WheelsApp_Backend.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("Address_Id");

                    b.HasOne("WheelsApp_Backend.Models.NextOfKin", "Next_of_kin")
                        .WithMany()
                        .HasForeignKey("Next_of_kinKin_id");
                });
#pragma warning restore 612, 618
        }
    }
}
