// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WheelsApp_Backend.Models;

namespace WheelsApp_Backend.Migrations
{
    [DbContext(typeof(WheelsContext))]
    partial class WheelsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WheelsApp_Backend.Models.User", b =>
                {
                    b.Property<long>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account_status");

                    b.Property<string>("Date_created");

                    b.Property<string>("Email");

                    b.Property<string>("First_name");

                    b.Property<long>("Id_number");

                    b.Property<string>("Last_name");

                    b.Property<string>("Password");

                    b.Property<int?>("Role");

                    b.Property<string>("Sex");

                    b.Property<string>("Telephone");

                    b.Property<string>("Telephone_2");

                    b.Property<string>("Username");

                    b.HasKey("User_Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
